(() => {
  const S=window.LH2;if(!S)return;
  let categoryId=null,removedMedia=[],historyGuide=null,deckIndex=null;

  const fmt=v=>{try{return new Intl.DateTimeFormat("sv-SE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}catch{return v||"Okänd tid"}};
  const close=id=>document.getElementById(id)?.classList.add("hidden");

  function ensureGuideOrder(){if(!data.guideOrder||typeof data.guideOrder!=="object"||Array.isArray(data.guideOrder))data.guideOrder={};(data.categories||[]).forEach(c=>{const keys=Object.entries(data.pages||{}).filter(([,p])=>p.group===c.id).map(([k])=>k),cur=Array.isArray(data.guideOrder[c.id])?data.guideOrder[c.id]:[],out=cur.filter((k,i)=>keys.includes(k)&&cur.indexOf(k)===i);keys.forEach(k=>{if(!out.includes(k))out.push(k)});data.guideOrder[c.id]=out})}

  async function safeSite(){const before=S.clone(data);try{data.settings.brandName=document.getElementById("editBrandName").value.trim()||data.settings.brandName;data.settings.brandSub=document.getElementById("editBrandSub").value.trim();data.settings.heroTitle=document.getElementById("editHeroTitle").value.trim();data.settings.heroText=document.getElementById("editHeroText").value.trim();await S.save();const m=document.getElementById("editSiteModal");if(m)m.dataset.dirty="0";closeModal("editSiteModal");renderHome()}catch(e){data=before;renderHome();toast(e.message||"Kunde inte spara sidhuvudet.")}}

  async function safeCategory(){const name=document.getElementById("categoryName")?.value.trim()||"",layout=document.getElementById("categoryLayout")?.value==="large"?"large":"compact";if(!name)return toast("Skriv ett namn på kategorin.");const before=S.clone(data);try{if(categoryId){const c=data.categories?.find(x=>x.id===categoryId);if(!c)throw new Error("Kategorin kunde inte hittas.");c.title=name;c.layout=layout}else{const id=S.uid("cat");data.categories.push({id,title:name,layout});if(!Array.isArray(data.homeLayoutV2))data.homeLayoutV2=["hero",...(data.homeLayout||[])];data.homeLayoutV2.push(`cat:${id}`);data.homeLayout=data.homeLayoutV2.filter(r=>r!=="hero")}await S.save();const m=document.getElementById("categoryEditModal");if(m)m.dataset.dirty="0";closeModal("categoryEditModal");renderHome()}catch(e){data=before;renderHome();toast(e.message||"Kunde inte spara kategorin.")}}

  async function createGuide(group){const cat=data.categories?.find(c=>c.id===group);if(!cat)return;const before=S.clone(data),key=S.uid("guide");try{data.pages[key]={group,icon:"•",kicker:cat.title,title:"Ny guide",summary:"Skriv en kort beskrivning.",intro:"Skriv en kort introduktion till guiden.",steps:[{title:"Första steget",text:"Skriv instruktionen här."}],note:"",noteType:"info"};ensureGuideOrder();data.guideOrder[group].push(key);await S.save();renderHome();removedMedia=[];openEditPage(key)}catch(e){data=before;renderHome();toast(e.message||"Kunde inte skapa guiden.")}}

  function captureSteps(){return [...document.querySelectorAll("#stepEditor .stepedit")].map(el=>({title:el.querySelector(".stepTitle")?.value.trim()||"",text:el.querySelector(".stepText")?.value.trim()||"",imageUrl:el.querySelector(".stepImageUrl")?.value||"",imagePath:el.querySelector(".stepImagePath")?.value||"",imageCaption:el.querySelector(".stepImageCaption")?.value.trim()||"",videoUrl:el.querySelector(".stepVideoUrl")?.value||"",videoPath:el.querySelector(".stepVideoPath")?.value||"",videoCaption:el.querySelector(".stepVideoCaption")?.value.trim()||"",removeImage:el.dataset.removeImage==="1",removeVideo:el.dataset.removeVideo==="1"}))}
  function redrawSteps(steps){renderStepEditor(steps.map(s=>({title:s.title,text:s.text,...(s.imageUrl?{imageUrl:s.imageUrl,imagePath:s.imagePath,imageCaption:s.imageCaption}:{}),...(s.videoUrl?{videoUrl:s.videoUrl,videoPath:s.videoPath,videoCaption:s.videoCaption}:{})})));[...document.querySelectorAll("#stepEditor .stepedit")].forEach((el,i)=>{const s=steps[i];if(!s)return;if(s.removeImage){el.dataset.removeImage="1";const x=el.querySelector(".stepImageUrl")?.closest(".shot-editor")?.querySelector(".current-shot");if(x)x.style.display="none"}if(s.removeVideo){el.dataset.removeVideo="1";const x=el.querySelector(".stepVideoUrl")?.closest(".shot-editor")?.querySelector(".current-shot");if(x)x.style.display="none"}})}

  async function safeGuide(){
    const btn=document.getElementById("savePageBtn");if(!btn||!editingPageKey||!data.pages?.[editingPageKey])return;const before=S.clone(data),uploaded=[],deleteAfter=[...removedMedia];btn.disabled=true;btn.textContent="Sparar…";
    try{
      const out=[],editors=[...document.querySelectorAll("#stepEditor .stepedit")];
      for(let i=0;i<editors.length;i++){
        const el=editors[i],title=el.querySelector(".stepTitle")?.value.trim()||"",text=el.querySelector(".stepText")?.value.trim()||"";let imageUrl=el.querySelector(".stepImageUrl")?.value||"",imagePath=el.querySelector(".stepImagePath")?.value||"",videoUrl=el.querySelector(".stepVideoUrl")?.value||"",videoPath=el.querySelector(".stepVideoPath")?.value||"";const imageCaption=el.querySelector(".stepImageCaption")?.value.trim()||"",videoCaption=el.querySelector(".stepVideoCaption")?.value.trim()||"",imageFile=el.querySelector(".stepImageFile")?.files?.[0],videoFile=el.querySelector(".stepVideoFile")?.files?.[0];
        if(imageFile){const u=await S.upload(imageFile,editingPageKey,i,"image");uploaded.push(u.path);if(imagePath)deleteAfter.push(imagePath);imagePath=u.path;imageUrl=u.url}else if(el.dataset.removeImage==="1"){if(imagePath)deleteAfter.push(imagePath);imagePath=imageUrl=""}
        if(videoFile){const u=await S.upload(videoFile,editingPageKey,i,"video");uploaded.push(u.path);if(videoPath)deleteAfter.push(videoPath);videoPath=u.path;videoUrl=u.url}else if(el.dataset.removeVideo==="1"){if(videoPath)deleteAfter.push(videoPath);videoPath=videoUrl=""}
        if(title||text||imageUrl||videoUrl){const s={title,text};if(imageUrl){s.imageUrl=imageUrl;s.imagePath=imagePath;if(imageCaption)s.imageCaption=imageCaption}if(videoUrl){s.videoUrl=videoUrl;s.videoPath=videoPath;if(videoCaption)s.videoCaption=videoCaption}out.push(s)}
      }
      const p=data.pages[editingPageKey],oldGroup=p.group;p.group=document.getElementById("editPageGroup")?.value||p.group;p.icon=document.getElementById("editPageIcon").value.trim();p.kicker=document.getElementById("editPageKicker").value.trim();p.title=document.getElementById("editPageTitle").value.trim();p.summary=document.getElementById("editPageSummary").value.trim();p.intro=document.getElementById("editPageIntro").value.trim();p.steps=out;p.note=document.getElementById("editPageNote").value.trim();p.noteType=document.getElementById("editPageNoteType").value;
      if(oldGroup!==p.group){ensureGuideOrder();data.guideOrder[oldGroup]=(data.guideOrder[oldGroup]||[]).filter(k=>k!==editingPageKey);if(!data.guideOrder[p.group].includes(editingPageKey))data.guideOrder[p.group].push(editingPageKey)}
      await S.save();await S.deleteStorage(deleteAfter);removedMedia=[];const m=document.getElementById("editPageModal");if(m)m.dataset.dirty="0";closeModal("editPageModal");renderHome();if(currentPage===editingPageKey)renderPage(currentPage);
    }catch(e){data=before;await S.deleteStorage(uploaded);renderHome();if(currentPage&&data.pages?.[currentPage])renderPage(currentPage);console.error(e);toast(e.message||"Kunde inte spara guiden.")}
    finally{btn.disabled=false;btn.textContent="Spara"}
  }

  function historyModal(){if(document.getElementById("v2HistoryModal"))return;document.body.insertAdjacentHTML("beforeend",`<div class="modalback hidden" id="v2HistoryModal"><div class="modal"><div class="modalhead"><h2 id="v2HistoryTitle">Versionshistorik</h2><button class="close" id="v2HistoryClose" type="button">×</button></div><div class="modalbody"><div class="v2-note" id="v2HistoryNote"></div><div id="v2HistoryList" class="v2-list"></div></div><div class="modalfooter"><button class="btn" id="v2HistoryDone" type="button">Stäng</button></div></div></div>`);document.getElementById("v2HistoryClose").onclick=()=>close("v2HistoryModal");document.getElementById("v2HistoryDone").onclick=()=>close("v2HistoryModal")}
  function openHistory(key=null){S.ensureData();historyModal();historyGuide=key;document.getElementById("v2HistoryTitle").textContent=key?`Historik · ${data.pages?.[key]?.title||"Guide"}`:"Versionshistorik";document.getElementById("v2HistoryNote").textContent=key?"Återställ bara den här guiden. Den nuvarande versionen sparas automatiskt så återställningen kan ångras.":"De senaste 20 sparade versionerna av sidan finns här.";let rows=data.versionHistory||[];if(key){let prev=JSON.stringify(data.pages?.[key]||null);rows=rows.filter(r=>{const p=r.snapshot?.pages?.[key];if(!p)return false;const v=JSON.stringify(p);if(v===prev)return false;prev=v;return true})}document.getElementById("v2HistoryList").innerHTML=rows.length?rows.map(r=>`<div class="v2-list-item"><div><strong>${S.esc(fmt(r.at))}</strong><small>${S.esc(r.by||"Admin")}</small></div><button class="btn small primary" data-v2-history="${S.esc(r.id)}" type="button">Återställ</button></div>`).join(""):'<div class="trash-empty">Ingen tidigare version finns ännu.</div>';document.getElementById("v2HistoryModal").classList.remove("hidden")}
  async function restoreHistory(id){const rec=(data.versionHistory||[]).find(r=>r.id===id);if(!rec?.snapshot)return;const before=S.clone(data);try{if(historyGuide){const p=rec.snapshot.pages?.[historyGuide];if(!p)return toast("Guiden finns inte i den versionen.");if(!confirm("Återställa guiden till den här versionen?"))return;data.pages[historyGuide]=S.clone(p)}else{if(!confirm("Återställa hela sidan till den här versionen?"))return;const h=data.versionHistory;data=S.clone(rec.snapshot);data.versionHistory=h;S.ensureData()}await S.save();close("v2HistoryModal");renderHome();if(currentPage&&data.pages?.[currentPage])renderPage(currentPage);toast("Versionen är återställd.")}catch(e){data=before;renderHome();toast(e.message||"Kunde inte återställa versionen.")}}

  function globalsModal(){if(document.getElementById("v2GlobalsModal"))return;document.body.insertAdjacentHTML("beforeend",`<div class="modalback hidden" id="v2GlobalsModal"><div class="modal"><div class="modalhead"><h2>Smarta variabler</h2><button class="close" id="v2GlobalsClose" type="button">×</button></div><div class="modalbody"><div class="v2-note">Skriv exempelvis <code>{{TRICASTER_IP}}</code> i en guide. Ändra värdet här så uppdateras det överallt. Lägg inte lösenord eller streamnycklar här.</div><div id="v2GlobalsRows"></div><button class="btn small" id="v2GlobalAdd" type="button">+ Variabel</button></div><div class="modalfooter"><button class="btn" id="v2GlobalsCancel" type="button">Avbryt</button><button class="btn primary" id="v2GlobalsSave" type="button">Spara</button></div></div></div>`);const c=()=>close("v2GlobalsModal");document.getElementById("v2GlobalsClose").onclick=c;document.getElementById("v2GlobalsCancel").onclick=c;document.getElementById("v2GlobalAdd").onclick=()=>globalRow("","");document.getElementById("v2GlobalsRows").onclick=e=>e.target.closest("[data-remove-global]")?.closest(".v2-global-row")?.remove();document.getElementById("v2GlobalsSave").onclick=async()=>{const before=S.clone(data);try{const g={};document.querySelectorAll("#v2GlobalsRows .v2-global-row").forEach(r=>{const k=r.querySelector(".v2-global-key").value.trim().toUpperCase().replace(/[^A-Z0-9_]/g,"_"),v=r.querySelector(".v2-global-value").value.trim();if(k)g[k]=v});data.globals=g;await S.save();c();renderHome();if(currentPage)renderPage(currentPage)}catch(e){data=before;toast(e.message||"Kunde inte spara variablerna.")}}}
  function globalRow(k,v){const d=document.createElement("div");d.className="v2-global-row";d.innerHTML=`<input class="v2-global-key" placeholder="TRICASTER_IP" value="${S.esc(k)}"><input class="v2-global-value" placeholder="Värde" value="${S.esc(v)}"><button class="btn small danger" data-remove-global type="button">×</button>`;document.getElementById("v2GlobalsRows").appendChild(d)}
  function openGlobals(){S.ensureData();globalsModal();const rows=document.getElementById("v2GlobalsRows");rows.innerHTML="";Object.entries(data.globals||{}).forEach(([k,v])=>globalRow(k,v));if(!rows.children.length)globalRow("TRICASTER_IP","");document.getElementById("v2GlobalsModal").classList.remove("hidden")}

  function deckModal(){if(document.getElementById("v2DeckModal"))return;document.body.insertAdjacentHTML("beforeend",`<div class="modalback hidden" id="v2DeckModal"><div class="modal"><div class="modalhead"><h2 id="v2DeckHead">Stream Deck-knapp</h2><button class="close" id="v2DeckClose" type="button">×</button></div><div class="modalbody"><div class="field"><label>Namn</label><input id="v2DeckLabel" maxlength="40"></div><div class="field"><label>Förklaring</label><textarea id="v2DeckDesc"></textarea></div><div class="field"><label>Färg</label><select id="v2DeckColor"><option value="neutral">Neutral</option><option value="purple">Lila</option><option value="blue">Blå</option><option value="green">Grön</option><option value="red">Röd</option><option value="yellow">Gul</option></select></div></div><div class="modalfooter"><button class="btn" id="v2DeckClear" type="button">Töm</button><div style="flex:1"></div><button class="btn" id="v2DeckCancel" type="button">Avbryt</button><button class="btn primary" id="v2DeckSave" type="button">Spara</button></div></div></div>`);const c=()=>close("v2DeckModal");document.getElementById("v2DeckClose").onclick=c;document.getElementById("v2DeckCancel").onclick=c;document.getElementById("v2DeckClear").onclick=()=>{document.getElementById("v2DeckLabel").value="";document.getElementById("v2DeckDesc").value="";document.getElementById("v2DeckColor").value="neutral"};document.getElementById("v2DeckSave").onclick=async()=>{if(deckIndex===null)return;const before=S.clone(data);try{data.streamDeck.buttons[deckIndex]={label:document.getElementById("v2DeckLabel").value.trim(),description:document.getElementById("v2DeckDesc").value.trim(),accent:document.getElementById("v2DeckColor").value};await S.save();c();if(currentPage)renderPage(currentPage)}catch(e){data=before;toast(e.message||"Kunde inte spara knappen.")}}}
  function openDeck(i){deckModal();deckIndex=i;const b=data.streamDeck.buttons[i]||{};document.getElementById("v2DeckHead").textContent=`Stream Deck · knapp ${i+1}`;document.getElementById("v2DeckLabel").value=b.label||"";document.getElementById("v2DeckDesc").value=b.description||"";document.getElementById("v2DeckColor").value=b.accent||"neutral";document.getElementById("v2DeckModal").classList.remove("hidden")}
  function deckPage(key){if(key!=="equipment")return;S.ensureData();const body=document.getElementById("pageBody");if(!body)return;document.getElementById("v2DeckMap")?.remove();const sec=document.createElement("section");sec.id="v2DeckMap";sec.className="panel";sec.innerHTML=`<h2>Stream Deck XL · 32 knappar</h2><p>${admin?"Klicka på en knapp för att redigera vad den gör.":"Klicka på en knapp för att läsa vad den gör."}</p><div class="v2-deck-scroll"><div class="v2-deck-grid">${data.streamDeck.buttons.map((b,i)=>`<button class="v2-deck-key v2-deck-${S.esc(b.accent||"neutral")}" data-v2-deck="${i}" type="button"><span>${S.esc(b.label||String(i+1))}</span><small>${b.label?`#${i+1}`:"Ej inställd"}</small></button>`).join("")}</div></div><div id="v2DeckDetail" class="v2-deck-detail">Välj en knapp för att se beskrivningen.</div>`;body.appendChild(sec);S.applyVars(sec)}
  S.hooks.page.push(deckPage);

  function adminsModal(){if(document.getElementById("v2AdminsModal"))return;document.body.insertAdjacentHTML("beforeend",`<div class="modalback hidden" id="v2AdminsModal"><div class="modal"><div class="modalhead"><h2>Användare & roller</h2><button class="close" id="v2AdminsClose" type="button">×</button></div><div class="modalbody"><div class="v2-note">Ägare kan bjuda in fler admins. Första gången krävs <code>supabase-v2.sql</code> i Supabase och miljövariabeln <code>SUPABASE_SERVICE_ROLE_KEY</code> i Netlify.</div><div class="v2-admin-invite"><input id="v2AdminEmail" type="email" placeholder="namn@example.com"><button class="btn primary" id="v2AdminInvite" type="button">Bjud in admin</button></div><div id="v2AdminsList" class="v2-list"></div></div><div class="modalfooter"><button class="btn" id="v2AdminsDone" type="button">Stäng</button></div></div></div>`);const c=()=>close("v2AdminsModal");document.getElementById("v2AdminsClose").onclick=c;document.getElementById("v2AdminsDone").onclick=c;document.getElementById("v2AdminInvite").onclick=async()=>{const email=document.getElementById("v2AdminEmail").value.trim();if(!email)return toast("Skriv en e-postadress.");try{await adminApi("invite",{email});document.getElementById("v2AdminEmail").value="";await loadAdmins();toast("Admininbjudan skickad.")}catch(e){toast(e.message||"Kunde inte bjuda in admin.")}};document.getElementById("v2AdminsList").addEventListener("change",async e=>{const s=e.target.closest("[data-admin-role]");if(!s)return;try{await adminApi("setRole",{userId:s.dataset.adminRole,role:s.value});await loadAdmins()}catch(err){toast(err.message||"Kunde inte ändra rollen.");await loadAdmins()}});document.getElementById("v2AdminsList").addEventListener("click",async e=>{const b=e.target.closest("[data-remove-admin]");if(!b||!confirm("Ta bort adminbehörigheten?"))return;try{await adminApi("remove",{userId:b.dataset.removeAdmin});await loadAdmins()}catch(err){toast(err.message||"Kunde inte ta bort admin.")}})}
  async function adminApi(action,payload={}){const{data:{session}}=await S.supa.auth.getSession();if(!session?.access_token)throw new Error("Du är inte inloggad.");const r=await fetch("/.netlify/functions/admin-users",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action,...payload})});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.error||"Adminfunktionen är inte konfigurerad ännu.");return b}
  async function loadAdmins(){const list=document.getElementById("v2AdminsList");list.innerHTML='<div class="trash-empty">Laddar…</div>';try{const r=await adminApi("list"),u=r.users||[];list.innerHTML=u.length?u.map(x=>`<div class="v2-list-item"><div><strong>${S.esc(x.email||x.id)}</strong><small>${S.esc(x.id)}</small></div><div class="v2-admin-actions"><select data-admin-role="${S.esc(x.id)}"><option value="admin" ${x.role==="admin"?"selected":""}>Admin</option><option value="owner" ${x.role==="owner"?"selected":""}>Ägare</option></select><button class="btn small danger" data-remove-admin="${S.esc(x.id)}" type="button">Ta bort</button></div></div>`).join(""):'<div class="trash-empty">Inga admins hittades.</div>'}catch(e){list.innerHTML=`<div class="trash-empty">${S.esc(e.message||"Kunde inte läsa admins.")}</div>`}}
  async function openAdmins(){adminsModal();document.getElementById("v2AdminsModal").classList.remove("hidden");await loadAdmins()}

  function adminTools(){if(!admin)return;const view=document.getElementById("adminView");if(!view)return;let p=document.getElementById("v2AdminTools");if(!p){p=document.createElement("div");p.id="v2AdminTools";p.className="panel";p.innerHTML='<h2>Verktyg</h2><div class="v2-tools"><button class="btn" id="v2GlobalsBtn" type="button">Smarta variabler</button><button class="btn" id="v2HistoryBtn" type="button">Versionshistorik</button><button class="btn" id="v2AdminsBtn" type="button">Användare & roller</button></div><p class="hint">Stream Deck-kartan finns under Utrustningen. Textblock flyttas och storleksändras direkt på startsidan.</p>';view.appendChild(p);document.getElementById("v2GlobalsBtn").onclick=openGlobals;document.getElementById("v2HistoryBtn").onclick=()=>openHistory();document.getElementById("v2AdminsBtn").onclick=openAdmins}document.getElementById("v2AdminsBtn")?.classList.toggle("hidden",S.state.role!=="owner");S.updateIdentity()}
  S.hooks.admin.push(adminTools);

  function guideHistoryBtn(){const f=document.querySelector("#editPageModal .modalfooter");if(!f||document.getElementById("v2GuideHistory"))return;const b=document.createElement("button");b.className="btn";b.id="v2GuideHistory";b.type="button";b.textContent="Historik";f.insertBefore(b,document.getElementById("savePageBtn"));b.onclick=()=>editingPageKey&&openHistory(editingPageKey)}

  const css=document.createElement("style");css.textContent=`.v2-tools{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.v2-list{display:grid;gap:9px}.v2-list-item{display:flex;align-items:center;justify-content:space-between;gap:12px;border:1px solid #2a405c;border-radius:13px;background:#0b1829;padding:12px}.v2-list-item small{display:block;color:#93a6bf;margin-top:3px}.v2-global-row{display:grid;grid-template-columns:1fr 1.5fr auto;gap:8px;margin-bottom:8px}.v2-global-row input,.v2-admin-invite input,.v2-admin-actions select{border:1px solid #2a3d58;border-radius:10px;padding:9px 10px;background:#091523;color:#f3f6fb}.v2-admin-invite{display:grid;grid-template-columns:1fr auto;gap:8px;margin-bottom:14px}.v2-admin-actions{display:flex;gap:8px;align-items:center}.v2-deck-scroll{overflow-x:auto;padding-bottom:8px}.v2-deck-grid{display:grid;grid-template-columns:repeat(8,86px);grid-template-rows:repeat(4,72px);gap:10px;min-width:758px;margin-top:16px}.v2-deck-key{border:1px solid #344862;border-radius:13px;background:#111d2c;color:#f3f6fb;padding:7px;display:flex;flex-direction:column;justify-content:center;align-items:center;gap:4px;font-weight:800;text-align:center}.v2-deck-key span{font-size:12px;line-height:1.2}.v2-deck-key small{font-size:10px;color:#9fb0c5}.v2-deck-purple{background:#271f48;border-color:#6856b6}.v2-deck-blue{background:#122c49;border-color:#356a9f}.v2-deck-green{background:#153229;border-color:#39735c}.v2-deck-red{background:#3a1c25;border-color:#8b4256}.v2-deck-yellow{background:#392d16;border-color:#826936}.v2-deck-detail{margin-top:12px;padding:12px;border-radius:12px;background:#091523;border:1px solid #293f5b}.v2-deck-detail strong{display:block;margin-bottom:4px}.v2-deck-detail p{margin:0;color:#9fb0c5}@media(max-width:720px){.v2-global-row,.v2-admin-invite{grid-template-columns:1fr}.v2-list-item{align-items:stretch;flex-direction:column}.v2-admin-actions{align-items:stretch;flex-direction:column}.v2-tools .btn{width:100%}}`;document.head.appendChild(css);

  document.addEventListener("click",async e=>{
    const editCat=e.target.closest("[data-edit-category]");if(editCat){categoryId=editCat.dataset.editCategory||null;setTimeout(()=>{const n=document.getElementById("categoryDeleteNote");if(n&&categoryId)n.textContent="Om du tar bort kategorin flyttas den och alla guider i den till Papperskorgen."},0)}
    if(e.target.closest("#addCategoryBtn"))categoryId=null;
    const add=e.target.closest("[data-v2-add-guide]");if(add&&admin){e.preventDefault();e.stopImmediatePropagation();await createGuide(add.dataset.v2AddGuide);return}
    const h=e.target.closest("[data-v2-history]");if(h&&admin){e.preventDefault();await restoreHistory(h.dataset.v2History);return}
    const deck=e.target.closest("[data-v2-deck]");if(deck){e.preventDefault();const i=Number(deck.dataset.v2Deck);if(admin)openDeck(i);else{const b=data.streamDeck.buttons[i]||{},d=document.getElementById("v2DeckDetail");if(d)d.innerHTML=`<strong>${S.esc(S.resolve(b.label||`Knapp ${i+1}`))}</strong><p>${S.esc(S.resolve(b.description||"Ingen beskrivning ännu."))}</p>`}return}
    const addStep=e.target.closest("#addStepBtn");if(addStep&&admin){e.preventDefault();e.stopImmediatePropagation();const st=captureSteps();st.push({title:"Nytt steg",text:"Skriv instruktionen här."});redrawSteps(st);S.markDirty();return}
    const remove=e.target.closest("[data-remove-step]");if(remove&&admin){e.preventDefault();e.stopImmediatePropagation();const st=captureSteps(),i=Number(remove.dataset.removeStep),r=st[i];if(r?.imagePath)removedMedia.push(r.imagePath);if(r?.videoPath)removedMedia.push(r.videoPath);st.splice(i,1);redrawSteps(st);S.markDirty();return}
    if(e.target.closest("[data-remove-image],[data-remove-video]"))S.markDirty();
    if(e.target.closest("[data-edit],#editPageBtn,[data-v2-add-guide]"))removedMedia=[];
  },true);

  window.addEventListener("load",()=>setTimeout(()=>{
    const savePage=document.getElementById("savePageBtn"),saveSite=document.getElementById("saveSiteBtn"),saveCat=document.getElementById("saveCategoryBtn");if(savePage)savePage.onclick=safeGuide;if(saveSite)saveSite.onclick=safeSite;if(saveCat)saveCat.onclick=safeCategory;guideHistoryBtn();adminTools();
  },40));
})();